version: '3'

services:
  api:
    image: tomcat:9.0.73-jdk17-temurin-jammy
    volumes:
      - "./webapp:/usr/local/tomcat/webapps/ROOT"
      - "./resources/logback.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/logback.xml"
      - "./resources/MANIFEST.MF:/usr/local/tomcat/webapps/ROOT/META-INF/MANIFEST.MF"
      - "./resources/guitarshop.p12:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/guitarshop.p12"
    ports:
      - "8443:8443"
    env_file:
      - guitarshop.env

  db:
    image: postgres:latest

networks:
  network:
